ARG BASE_IMAGE="ghcr.io/gbraad-devenv/centos/base"
ARG BASE_VERSION="stream9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

USER gbraad

RUN git clone https://github.com/gbraad/dotfiles ~/.dotfiles \
    && rm -f ~/.zshrc \
    && ~/.dotfiles/install.sh

ENTRYPOINT [ "/bin/zsh" ]
