ARG BASE_IMAGE="ghcr.io/gbraad-dotfiles/centos"
ARG BASE_VERSION="stream9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/centos"

USER root

RUN dnf install -y \
        mc screen links lynx \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN dnf install -y \
        openssh-server \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo \
    && dnf install -y \
       gh \
    && dnf clean all \
    && rm -rf /var/cache/yum

COPY assets/tailscaled /etc/init.d/tailscaled
RUN mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale
